# Generated by Django 4.2.5 on 2023-09-29 08:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_customuser_delete_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='RegisterUser',
        ),
    ]
